supriya46788/BakeGenuis-AI

index.html
style.css

This PR adds a soft, candy-inspired loading spinner to enhance the user experience during page load.
fix issue #5 
**Changes made:**
Implemented a full-screen loading overlay (#loading-spinner) with fade-out effect.
Added rotating circular spinner with transparent center and white outline.
Added floating sweets animation (cupcakes, donuts, candies) for a playful effect.
Included JavaScript to:
Randomly generate floating sweets positions and animations.
Automatically remove the loader after a set delay.
Used theme colors (#ff7aa2, soft pinks) to match site design.
**ScreenRecording**
https://github.com/user-attachments/assets/27496237-3ec3-4dcb-9ee8-53593755a6ae
kindly merge it @supriya46788 under gssoc'25

feat: add sweet-themed loading spinner with floating sweets animation

---

js/scale.js

**When entering fractions such as 1/2 cup sugar or 3/4 cup flour, the recipe scaler parses them incorrectly. The regex matches the fraction, but parseFloat("1/2") returns 1, not 0.5.**
Before : 
After : 
closes #84

Fix Variable Shadowing and Document Fraction Parsing in scale.js

---

js/customize.js

This PR fixes the issue where clicking Reset to Defaults did not properly restore the original ingredient values. Previously, the defaults were being mutated in memory during runtime (e.g., after brand adjustments or manual overrides).
Solution : 
Introduced deep cloning when loading defaults to prevent mutation.
Updated loadIngredients to always return a fresh copy of defaults:
closes #108

Bug Fix: Reset to Defaults Restores Original Ingredients in customize.js

---

css/about.css
css/auth.css
css/convert.css
css/customize.css
css/feedback.css
css/index.css
css/recipe_hub.css
css/scale.css

Improved the sticky navbar implementation to ensure consistent behavior across all pages and devices, with proper spacing, z-index management, and mobile responsiveness.
**Key Changes:**
- Increased z-index from 100 → 1000 to keep the navbar above all content
- Adjusted content spacing to prevent overlap (reduced unnecessary top padding)
- Improved mobile responsiveness with padding adjustments for smaller screens
- Standardized z-index hierarchy: navbar (1000), mobile nav (999), scroll button (999)
- Optimized mobile nav positioning to account for sticky navbar height
**Features Implemented:**
✅ Navbar remains sticky at the top during scroll
✅ Works consistently across all pages (Home, Convert, Scale, About, etc.)
✅ No content overlap — proper spacing maintained
✅ Fully …

Enhanced Sticky Navbar Implementation Across All Pages

---

css/index.css
css/recipe_hub.css

Fix: Community Recipes dark mode styling
🔹 Updated recipehub.css to ensure the Community Recipes cards correctly follow dark mode styling.
🔹 Previously, the cards remained white in dark mode → now they adapt seamlessly.
🔹 This improves UI consistency across the app and matches the behavior of other recipe sections.
Changes Made:
Adjusted background, text, and card styles in recipehub.css.
Verified on both light and dark modes with toggle.
**BEFORE**
**AFTER**

Fix: Applied dark mode styling to Community Recipes section (#209)

---

css/recipe_hub.css
html/recipe_hub.html

refers to issue #212 
On the Recipe Hub page, the filter box was rendering **below the recipe cards** instead of staying on top.  
- This issue appeared across all screen sizes.  
- Users could miss the filter box since its position was unintuitive.  
- Overall page layout looked inconsistent and impacted usability.  
- Moved the filter box to correctly appear **above the recipe cards** across all screen sizes.  
- Improved CSS to give the filter box a cleaner, more consistent look with the page design.  
- Ensured responsiveness for both desktop (2 columns) and mobile (single column).  
✅ Filter box is now always visible in the correct place.  
✅ Layout is clean and consistent.  
✅ Usability improved with enhanced styling.

Fix: Filter panel position & enhanced CSS styling

---

css/index.css
index.html

This PR introduces a loader page that appears for 7 seconds before the main page loads. The purpose of this loader is to improve the user's experience by providing visual feedback during content loading.
Key Features:
1. Loader displays for ~7 seconds
2. Smooth animation to indicate progress
3. Automatically redirects to the main content after the loading completes

Adding a loader animation

---

html/feedback.html

- Added validation rules for form fields:
- **Name**: must contain at least 3 characters
- **Feedback**: must contain at least 10 characters
- Prevented form submission until all validation rules are satisfied
Ensure that users provide meaningful input before submitting the feedback form.

Validate Feedback Form

---

css/about.css
css/recipe_hub.css

This PR standardizes the navbar button styles to ensure consistency across pages.
Both Feedback and Scale Now buttons now share the same dimensions, padding, and styling, resolving the size mismatch issue between recipe_hub.css and customize.css.
This PR closes issue #154 
1) Updated recipe_hub.css to match button styling used in customize.css.
2) Applied consistent padding, border-radius, and hover effects to maintain a uniform look.
3) Improved UI consistency and alignment in the navbar.
1) Verified on Recipe Hub page that Scale Now button matches Feedback button.
2) Checked on Customize page to ensure consistent styling across both views.
3) Confirmed responsive behavior on different screen sizes.
@supriya46788 kindly review and merge my PR.

Fix: unify Scale Now button style in recipe_hub.css

---

css/about.css
css/auth.css
css/index.css
html/about.html
html/login.html
index.html
js/index.js

- Adjusted navbar items (Convert Recipe, Customize, Recipe Hub, About, Feedback, Login, Sign Up, Scale Now) to ensure proper alignment and spacing.
- Fixed the issue where some buttons (Feedback, Login, Sign Up, Scale Now) appeared shifted.
- Updated the scroll button behavior to work bottom-to-top for smoother navigation flow.
- Ensured scroll button consistency across all pages.
This PR improves:
- UI/UX consistency
- Navigation clarity
- Professional appearance of the homepage and header.
Fixes : #270 
---

Fixed : Navbar Alignment and Scroll Button Consistency

---

css/about.css
html/about.html
js/about.js

##solved #265 issue
##description
1->Added clicked listner on Contributers cards , 
-.On clicked it will redirect to the ghithub profile of the contributer
https://github.com/user-attachments/assets/bc4525b9-f352-4ebf-8d58-ffac94bad6b2

Added Clicked function on cards of contributer -->redirect to ghithub profile

---

index.html

This pull request resolves the issue where the hero section title `"Welcome to BakeGenius.ai"` did not appear on the homepage.
* Corrected CSS properties that kept the hero title hidden (`width: 0; overflow: hidden`).
* Ensured the typing animation activates correctly by applying the `typing-active` class.
* Added a fallback text color for browsers without full gradient text support.
* Adjusted z-index to prevent the title from being covered by overlays.
With these changes, the welcome message is now clearly visible and animates as intended, improving the first impression for users landing on the site.
Reference
Before:
After
Fixes  #297 issue.

Fix:  "Welcome to BakeGenius.ai" not visible on homepage

---

about.html
assets/css/about.css
customize.html

This PR fixes the issue where social icons (LinkedIn, GitHub, etc.) appeared as colored blocks instead of proper icons. 
Fixes issue #415 
BEFORE:
AFTER:

fix: footer social icons display

---

scale.html

This PR fixes some minor bugs in CSS of scale recipes page including the inconsistent hover state of nav-links and body's background color.
Fixes #473
##Screenshots
Before:
After:

Fix some bugs in scale recipes page

---

index.html

made the home pages' footer mobile responsive

---

contact.html

**📝 Description**
This PR updates the Send Message button on the Contact us page to match the site’s current theme. The button color was previously inconsistent with the design system, which made it stand out awkwardly from other UI elements.
**Reference**
_Before_
_After_
Fixes #552 issue.

 Updated Send Message Button Color in Contact us section

---

assets/css/about.css

This PR fixes an inconsistency in dark mode styling on the About page footer.
* Updated social icons to match dark theme colors .
* Adjusted badge styles to align with other pages in dark mode.
* Also updated login button theme in dark mode
Fixes Issue #580 
1. Switch to dark mode.
2. Navigate to the *About page*.
3. Compare the footer with other pages (e.g., Home, customize).
4. Verify icons and badges now look consistent.

Fix: unify dark mode footer styles on About page

---

scale.html

This PR addresses issue #609 
---

Made the scale Recipes' footer mobile responsive

---

assets/css/about.css

**Description**
This PR fixes the issue where the hero heading was touching the navbar by adding top spacing to the hero section.
**Why This Fix?**
Previously, the hero section began immediately below the navbar, making the heading appear cramped. This adjustment improves visual hierarchy and readability by ensuring sufficient breathing room.
**Reference**
Before
After
Fixes #598 issue.

Fixed spacing between navbar and heading in About section

---

scale.html

This PR updates the CSS styling for social icons in dark theme mode on the Scale Recipe page. The changes improve visibility, contrast, and alignment with the overall dark theme design, ensuring better readability and consistent user experience.
fixes Issue #633
-  Updated CSS variables and classes for social icons in dark theme
-  Improved contrast to ensure icons are visible against dark backgrounds
-  Verified styling consistency between light and dark modes
BEFORE:
AFTER:

Update social icons CSS for dark theme consistency

---

about.html
assets/css/about.css
assets/js/about.js
convert.html
customize.html
faq.html
index.html
scale.html

Updated about.html | about.css | about.js | convert.html | customize.html | faq.html | scale.html | index.html for back to top/bottom
Tested locally all working fine

updated Back to top/bottom across all pages

---

assets/css/convert.css

Fix: Consistent footer badges in Convert Recipe section (dark & light mode)
This PR fixes the issue where the badges in the footer of the Convert Recipe section did not match those on other pages. The footer badges have now been updated to ensure consistency across the site.
**Reference:**
Fixes #736  issue.

Fix: Consistent footer badges in Convert Recipe section (dark & light mode)

---

assets/css/convert.css

This PR fixes the issue where the footer text on the convert recipe page was not visible in dark mode due to insufficient contrast.
Fixes Issue #768 
* Adjusted footer text color for dark mode.
* Ensured text maintains readability and accessibility.
* Verified styling consistency across light and dark themes.

Fix: Convert Recipe Page Footer Text Invisible in Dark Mode

---

about.html
contact.html
convert.html
customize.html
faq.html
feedback.html
helpcenter.html
index.html
privacypolicy.html
scale.html
toc.html

Closes: #802 
Ensured consistency in the footer navigation by adding "Contact Us" and "Help Center" links across all pages.
- Updated footer to include both "Contact Us" and "Help Center" across all the pages in the order:
Contact us
Help Center
Feedback
FAQ
Privacy Policy
Terms of Service
- Applied consistent icons and link structure
- Verified alignment and styling across all pages

Added consistent navigation links of contact Us and helpcenter across all the pages

---

index.html
js/firebase.js

- Created `js/firebase.js` with proper Firebase CDN module imports 
- Updated `index.html` to load Firebase as an ES module
- Added CORS error prevention guidance
- Launched the app locally via Live Server at http://127.0.0.1:5500 (shown in the attached screenshot).
- Opened the browser’s Developer Console (Chrome) to observe runtime behavior.
- Verified that Firebase initialized correctly
- Console shows “Firebase analytics initialized” and “Firebase initialized {projectId: "bakegeniusai"},” confirming the CDN-based imports in js/firebase.js are working.
- Logs include “Chatbot HTML created,” “Chatbot events bound,” “Welcome message added,” and finally “Chatbot initialized successfully.”
- Checked that no JavaScript or network errors appear in the console, which demonstrates the fixes to …

Fix Incorrect and Incomplete Setup Instructions #835

---

assets/js/convert.js

- Fixed small quantity conversion for vanilla extract, baking powder, and salt
- Updated conversion database with correct gram values per teaspoon
- Improved ingredient parsing logic for fractions and mixed numbers
- Added proper imperial unit conversion system
- Enhanced error handling and user feedback
Fixes the "Ambiguous Measurement" error that was occurring when converting recipes with small quantities. Small ingredients like vanilla extract, baking powder, and salt were showing 0g instead of proper gram values.
- **Fixed conversion logic** for small quantities (vanilla, baking powder, salt)
- **Updated conversion database** with correct gram values per teaspoon
- **Improved ingredient parsing** for fractions and mixed numbers
- **Added proper imperial unit conversion**
- **Enhanced …

Fix Ambiguous Measurement Error in Recipe Converter

---

assets/css/index.css

The overlapping of dark mode button on the landing over the title in the mobile view has been fixed 
##Screenshots

Fixed the overlapping of the dark mode button with the title
