supriya46788/BakeGenuis-AI

CODE_OF_CONDUCT.md
Hello @supriya46788 👋,
I have added a comprehensive CODE_OF_CONDUCT.md for the 🍰 BakeGenius AI – Precision Baking for Everyone project. This Code of Conduct is based on Contributor Covenant v2.1, but it has been extensively expanded and customized to reflect the collaborative, respectful, and innovative spirit of this project.
The document includes:
🌍 A clear statement of our community values and inclusivity principles.
📜 Detailed behavior guidelines for communication, collaboration, and respectful engagement.
⚖️ Transparent enforcement process with clear responsibilities for maintainers.
🛠 Examples of acceptable and unacceptable behaviors to avoid ambiguity.
📝 Attribution section acknowledging the Contributor Covenant and other inspiration sources.
📑 GitHub-friendly formatting with …
=> CODE_OF_CONDUCT FILE SUCCESSFULLY CREATED

CONTRIBUTING.md
🚀 PR Ready for Review & Merge
Hello @supriya46788 ,
I’ve added a detailed and GitHub-formatted CONTRIBUTING.md file for the BakeGenius AI project 🍰, following best practices from GitHub’s Open Source Guides.
This document includes:
📜 Code of Conduct reference
🤝 Ways to contribute
🛠 Getting started instructions
🔄 Clear contribution workflow
🎯 Coding & commit guidelines
🧪 Testing & review process
This will make it easier for new contributors to onboard and help maintain project quality.
Kindly review and merge when possible ✅
Thanks for your time & support! 🙌
— Aditya Verma
=> SUCCESSFULLY CREATED THE CONTRIBUTING.md FILE✅

about.html, convert.html, customize.html, index.html, scale.html
Add dark/light mode toggle button with localStorage support
=> Issue #12 resolved

index.html
hey @supriya46788 ,
issue no : #16 
Description:
This PR addresses the issue of poor text visibility in the feature cards section. Adjusted the text color and background contrast to improve readability across different screen sizes and themes.
Changes made:
Updated CSS for feature card text color
Enhanced background overlay for better contrast
Tested on light and dark modes to ensure consistent visibility
Please review and merge. Thanks!
=> Fix Text Visibility in Feature Cards 

recipe.html
I have made the required changes to the code:
Here in recipe.html, u have to add your api key, after that it will start working 
Thank you!!!
=> AI-generated recipes

.env.example, .gitignore, index.html, login.html, server/models/User.js, server/package-lock.json, server/package.json, server/routes/auth.js, server/server.js, signup.html
=> # added login and signup with Backend 

convert.html, customize.html, footer.html, recipe.html, scale.html
- Created a reusable footer component (`footer.html` + `footer.css`) to maintain consistency across the site.
- Added the footer to:
1. Convert Recipe page
2. Customize page
3. Scale Recipes page
- Ensured responsive design for desktop and mobile devices.
- Improves professionalism and visual consistency.
- Makes it easy to reuse the same footer for future pages without duplicating code.
- Gives users quick access to branding, contact info, and copyright.
- Footer text:
BakeGenius.ai — Baking meets AI: recipes, ideas, and inspiration to make your creations magical!
Address: 123 Kitchen Street, Food City, 45678
Email: contact@BakeGenius.com | Phone: +91 98765 43210
© 2025 BakeGenius.ai — All rights reserved.
Closes #33
=> Added reusable footer to Convert Recipe, Customize, and Scale Recipes pages

css/forgot.css, html/forgot.html, html/login.html, html/signup.html, js/forgot.js, js/login.js, js/signup.js
I have added the forgot password page and In Signup page password strength checker like strong, weak and medium.
Fixes #45
=> adding pages and features

css/convert.css, css/scale.css, html/convert.html, html/scale.html, js/convert.js, js/scale.js
Implemented a comprehensive nutritional breakdown feature that displays calories, macronutrients (protein, fat, carbohydrates), and sugar content for both converted and scaled recipes. This enhancement makes the application more valuable for health-conscious users and those tracking their dietary intake.
Key Features Added:
1. Real-time nutrition calculation based on ingredient weights
2. Color-coded nutrition display with beautiful gradient styling
3. Responsive design for mobile compatibility
4. Dark mode support
5. Automatic scaling of nutrition values when recipes are scaled
6. Comprehensive nutrition database for common baking ingredients
Fixed #29
=> Add Nutritional Breakdown Feature to Recipe Converter and Scale Pages

css/privacy.css, css/terms.css, html/privacy.html, html/terms.html, index.html
=> t&c and privacy policy

css/about.css, css/contact.css, html/about.html, html/contact.html
as i mention i created contact page and create the follow us links properly hope you like my work @supriya46788
=> add contact page and follow links

css/index.css, html/about.html, html/convert.html, html/customize.html, html/scale.html, index.html
This PR introduces a loader page that appears for 6–7 seconds before the main page loads. The purpose of this loader is to improve the user's experience by providing visual feedback during content loading.
Key Features:
1.Loader displays for ~6–7 seconds
2.Smooth animation to indicate progress
3.Automatically redirects to the main content after the loading completes
https://github.com/user-attachments/assets/5c4c30cc-3d04-4331-8766-08fb4c816ba3
=> Adding a loader animation before it shows the home page

css/index.css, html/about.html, html/convert.html, html/customize.html, html/scale.html, index.html
Reverts supriya46788/BakeGenuis-AI#77
=> Revert "Adding a loader animation before it shows the home page"

css/index.css, index.html
Issue number #66 
I have added how it works page on homepage  to clearly and visually explain our process to new users, reducing friction and encouraging them to start using the tool immediately.
=> Added how it works page on homepage

css/about.css, css/convert.css, css/customize.css, css/index.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/scale.html, index.html
Description:
Updated the project so that all pages now share the same unified footer.
Previously, different pages had inconsistent footers.
Ensured a single consistent footer design with links, newsletter, and social icons applied across the entire website.
Improves UI consistency and provides a smoother user experience.
=> Standardized Footer Across All Pages

css/about.css, css/convert.css, css/customize.css, css/index.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/scale.html, index.html
Solved issue #85 
@supriya46788 Could you check the changes made and update me anything needs to be changes
updated navbar
=> Enhanced Navbar with gradient, hover effects

css/about.css, html/about.html, js/about.js
I have successfully updated About Us page and added contributors section.
Fixes #68
=> Updated About Us page and added contributors section

css/recipe_hub.css, html/about.html, html/convert.html, html/customize.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html, index.html, js/recipe_hub.js
Created a new **Recipe Sharing Hub** page to build a community space for discovering, sharing, and saving recipes.
Implemented complete **search, filtering, social interaction, and personal cookbook features** with responsive design.
* **Discovery Tools**
* Advanced search by name, ingredients, tags, or creator
* Smart filters (difficulty, cook time, dietary needs)
* Trending & Featured recipe sections
* Sorting options (latest, most popular, highest rated)
* **Social Interactions**
* Like/unlike recipes with real-time updates
* Share recipes (native share API + clipboard fallback)
* Follow/unfollow creators
* Creator profile display with avatar
* **Personal Management**
* Save recipes to personal **Cookbook** (persistent via `localStorage`)
* Copy recipe details to clipboard
* …
=>  Feature Added: Recipe Sharing Hub Integration

css/about.css, css/auth.css, css/convert.css, css/customize.css, css/feedback.css, css/index.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/scale.html, html/signup.html, index.html, js/feedback.js
- Implemented a new Feedback Page in the website.
- Maintains the same UI/UX design consistency as other pages.
- Users can now submit their feedback easily.
- The page is fully responsive and works without breaking existing features.
- Verified that styling, layout, and navigation are consistent with the site.
Fixes : #105 
---
https://github.com/user-attachments/assets/a6c03f56-55c6-4366-923d-3f044d69449b
=> Added a dedicated feedback page to the website.

css/index.css, index.html
=> added scroll to top #90

js/about.js
Description:
Updated about.js code to remove dynamic background color change on hover in about section.
Issue Reference:
Fixes #111 
Changes made:
Deleted initNavLinkEffects() function from JavaScript file to improve user experience and UI.
=> Updated about.js code to remove dynamic color change of navbar anchor links.

css/auth.css, html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/recipe_hub.html, html/scale.html, index.html, js/auth.js
This PR integrates a SweetAlert2 confirmation dialog for logout across all pages of the site.
Changes Made
- Replaced the default alert/logout behavior with SweetAlert2.
- Added a confirmation dialog with the message: “Are you sure you want to log out?”
-   Options:
-     Yes, Logout → logs out.
-     Cancel → keeps the user on the same page.
- Applied the update globally so the feature works consistently on every page.
Fixes : #115 
---
=> Logout Confirmation with SweetAlert2

css/convert.css
Fix issue #160 
Updated the entire UI of the convert recipe page.
=> Update convert recipe

css/about.css, css/auth.css, css/convert.css, css/customize.css, css/feedback.css, css/index.css, css/recipe_hub.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html, index.html
=> Added logo redirection to home

css/auth.css, html/convert.html, html/customize.html, html/login.html, js/firebase.js
**Add Sign-In with Google using Firebase Authentication**  
- **Name:** Chaitanya
- **GitHub ID:** ChaitanyaBadukale777
- **Email ID (for communication):** chaitanyabadukale757@gmail.com
- **Participation Program (if any):** GSSOC'25
**What have you added or modified in this pull request?**  
- Integrated Google Sign-In using Firebase Authentication SDK.
- Updated the login UI to include a “Sign in with Google” button using external styles.
- Implemented authentication flow to handle Google login and session persistence.
- Added error handling for failed or canceled sign-in attempts.
- Enhanced overall user experience by enabling quick, one-click access for users with Google accounts.
Screenshot showing successful Google Sign-In integration in Firebase Authentication with user entry …
=> Add Sign-In with Google using Firebase Authentication

css/index.css, index.html
##solved issue #126 
##description 
1->Adding animation to home page 
2->Add animation to the icons
3->toggling on of scroll button on scrolling greater the 300px also added floating animation
##Screenshot
=> UI of home page and Backtotop enhances

css/about.css, js/about.js
This PR improves the “Our Contributors” section by:
Displaying only the contributor’s avatar and username.
Removing unnecessary text like contribution count.
Making contributor cards compact, side-by-side, and responsive.
Adding hover effect for better UI.
Ensuring text does not overflow with ellipsis.
Changes:
Updated about.js to only append img + username for each contributor.
Updated CSS (about.css) for .contributor-card and #contributors-container to create a neat horizontal layout.
closes #187
=> Big Fix : Contributor details fixed , private keys removed to prevent security issues

css/customize.css, js/customize.js
This update focuses on enhancing the Ingredient Density Editor section and the associated action buttons for a more consistent and visually appealing user experience.
1. **Styling improvements:**
- Updated the density editor container and form inputs to match the look and feel of the existing ingredient cards.
- Added hover and focus effects similar to the ingredient cards for visual consistency.
- Adjusted padding, border-radius, and shadows for a cleaner UI.
- Ensured mobile responsiveness for all buttons and input fields.
2. **Success / Feedback Messages:**
- Modified the “Apply Changes” message to display in the same color as the Apply button, differentiating it from the default green Save message.
- Maintained JS logic for showing messages, with CSS changes for color, size, and …
=> Ingredient Density Editor & Action Buttons: Styling and Dynamic Feedback

js/auth.js
This PR closes the issue #178 
-This version of code will not accept invalid domains like A@gml.com
- It will only accept valid email domains like @gml.com, @example.org, @company.in
=> Added email domain validation

css/auth.css, css/recipe_hub.css
This pull request resolves UI inconsistencies that affected readability and design coherence in the application.
1. **Recipe Hub Section**
* Fixed the issue where text was not clearly visible due to poor contrast with the background.
* Updated styling to ensure proper visibility across both light and dark themes.
2. **Convert Recipe & Customize Section**
* Adjusted the **"Continue with Google"** button color to match the overall theme palette.
* Improved consistency of button styling with other primary actions across the app.
* Improves **accessibility** by ensuring text is legible in all themes.
* Enhances **visual consistency**, preventing mismatched elements from breaking the user experience.
* Provides a more polished and professional **UI look and feel**.
Screenshots
Before
After: …
=> UI Fix: Enhanced Recipe Hub text visibility & align Google button styling with theme

css/convert.css, css/feedback.css, css/index.css, css/recipe_hub.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html, index.html, js/auth.js
**Description** :
- After login, Login and Sign Up buttons should be hidden, and only Hi, [Username] + Logout should be visible.
- Navbar should have proper alignment, spacing, and consistent styling for a cleaner UI/UX.
- Scale Now button should be available on all pages with proper UI design.
- Logout should show a proper SweetAlert confirmation.
**Changes Implemented:**
- Fixed login/logout flow → now shows correct buttons after login.
- Corrected navbar alignment and made UI consistent across all pages.
- Added missing Scale Now button in all pages and improved its UI design.
- Debugged and added SweetAlert confirmation on logout.
- Verified and adjusted UI alignments to display correctly in Dark Mode as well.
Notes:
- This PR improves UI/UX consistency and authentication flow.
--- …
=> Alignment Fixes with Scale Now Button and Logout Enhancements

css/recipe_hub.css, html/recipe_hub.html
=> Updated recipe hub

css/convert.css, css/customize.css, css/index.css
This closes the issue #153 
- In this version of code I converted the px units in the nav bar to rem to make is consistent in all the zoom layouts
=> Did some adjustments for consistent layout

html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/recipe_hub.html, html/scale.html, index.html, js/feature.js
This PR introduces a smooth scrolling feature to enhance user experience across the website.
Changes Made:
Created feature.js to implement smooth scrolling behavior.
Integrated feature.js into all pages to ensure consistent scrolling functionality.
Improved overall UI/UX by providing a smoother navigation experience.
Why This Is Needed:
The smooth scrolling feature makes navigation feel more fluid and visually appealing, enhancing the user interface and overall usability of the site.
Testing:
Verified smooth scrolling on all supported pages.
Tested across major browsers to ensure compatibility.
Issue Reference:
Closes #179
=> Added SmoothScrolling feature

css/about.css, css/feedback.css, html/about.html, html/feedback.html
Hi, @supriya46788 
As mentioned in #206, I have fixed.
Please verify.
KIRTHI JC,
Gssoc'25, Contributor
=> Feedback and About pages uniformly fixed

html/recipe_hub.html, index.html
All related screenshots are attached in the issue . 
closes #216
=> Bug Fix : Inconsistency in header of the files index.html and recipes_hub.html

css/about.css, css/feature.css, css/index.css, html/about.html, html/login.html, html/signup.html, index.html, js/about.js, js/firebase.js
##solved issue #205 
##Description
1->Fix Unexpected behavior of border-right in about title 
2->enhance Ui of footer links added icons in footer , some styles
3->Fix continue with google button onhovering it will assest you to sign in with google(but only we have to provide authentication api -key) then it login with google
=> Fix unexpexted border-right in About , Enhance UI of navLnk of footer and Fix functionality of google btn

css/recipe_hub.css, html/recipe_hub.html, js/recipe_hub.js
Introduced a floating *“💡 Baking Tip”* button on the Recipe page that displays a random baking tip in a popup card. The feature enhances user engagement by providing helpful, bite-sized baking advice while maintaining the themed design of the site.
- Added a *floating button* (bottom-left) styled with a candy-pink gradient.  
- Designed a *popup card* with rounded corners, light candy colors, and subtle shadow.  
- Integrated *smooth fade/slide animations* for showing and hiding the popup.  
- Improved *UI alignment*:
- Bulb icon centered within the button.  
- Close button positioned neatly without overlapping text.  
- JavaScript logic selects and displays a *random tip* from a predefined list and each time the button is clicked, a different tip appears.
=> Added random baking tip popup feature on recipe page

CODE_CLEANUP_SUMMARY.md, css/floating_emoji_fix.css, html/about.html, html/customize.html, js/about.js, js/config.js, js/convert.js, js/feature.js, js/feedback.js, js/floating_emoji_footer_fix.js, js/scale.js, scale.html, server.js
=> Fix floating emojis overlapping the footer on multiple pages 

html/about.html, html/about_BACKUP_1224.html, html/about_BASE_1224.html, html/about_LOCAL_1224.html, html/about_REMOTE_1224.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html, index.html, js/mouse-trail.js, scale.html
- Implemented a reusable mouse trail effect using HTML Canvas.
- Added `mouse-trail.js` for modularity.
- Linked script in main layout so the effect applies globally across all pages.
- Ensured `pointer-events:none` so it does not interfere with buttons, forms, or other interactive elements.
- Adds a modern, polished aesthetic to the website 🎨
- Fun, interactive user experience ✨
- Easy to disable/remove if needed for performance.
https://github.com/user-attachments/assets/26f324f5-05dd-4139-920c-8ccecae9cb1e
Closes Issue: #31
=>  Added trailing mouse animation using HTML Canvas

index.html
This pull request improves the newsletter section of the footer to ensure visual and functional consistency across the entire website.
🔹 Key Updates
Standardized the newsletter footer design to match the global footer.
Fixed styling differences that caused misalignment between pages.
Improved overall layout for a cleaner and more cohesive user experience.
🔹 Why This Change Matters
Previously, the newsletter footer appeared inconsistent on different pages, which disrupted the site’s visual flow. With this update, users will now see a uniform footer design, strengthening the website’s branding and usability.
Reference:
Before:
After:
=> Enhance Newsletter Footer for Consistent Design Across All Pages

js/auth.js
=> fixed the visibility of 'scale now' button after the user logs in

css/index.css, index.html, js/index.js
Added a Scroll-to-Bottom button on the homepage with smooth scrolling. The button appears while scrolling down and takes users directly to the footer. 
✅ Improved navigation – users can quickly reach the footer without manually scrolling.
✅ Better user experience – smooth scrolling makes interaction seamless.
✅ Time-saving – especially useful on long pages with lots of content.
✅ Accessibility – helps users who may find manual scrolling tedious.
=> ✨ Added Scroll-to-Bottom button on homepage

css/index.css, css/scale.css, html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html
=> update feedback btn

README.md
This PR addresses issue #292 
Added a "Back to Top" badge at the end of the README that redirects users back to the top of the file for easier navigation.
=> Add back to top redirection in readme.md

js/about.js, public/css/about.css, views/about.html
##Solved #298 issue 
##Description 
1->Fix the issue of Creator social link in about page 
2->Added Search Functionality on top of contributers card section 
-->On searching you get the contributer ghithub profile if found. 
https://github.com/user-attachments/assets/8e3aed83-6219-41e0-a9e3-8aa2275a55b2
=> Fix creator social Link in and added search fuctionality in About page

public/css/index.css
Improved navbar menu design and consistency across desktop and mobile devices.
-> Standardized button and link styles with consistent padding and fonts
-> Enhanced Scale Now button prominence with blue gradient and better styling
-> Fixed navbar spacing and alignment for single-line desktop layout
-> Optimized dark mode toggle size and positioning
-> Improved mobile responsive design with proper spacing
-> Fixed mobile menu text cutting issues
-> Added hover effects for all navbar buttons
-> Made scroll-to-top button perfectly round with centered arrow
Closes #307
-> Tested on desktop (Chrome, Firefox)
-> Tested on mobile devices
-> Verified hover effects work properly
-> Confirmed no text cutting in mobile menu
=> [UI] Improve navbar menu design and consistency - fixes #307

public/css/about.css, public/css/feedback.css
Made navbar sticky on About and Feedback pages
=> made the navbar sticky in about page and feedback page

html/about.html, html/about_BACKUP_1224.html, html/about_BASE_1224.html, html/about_LOCAL_1224.html, html/about_REMOTE_1224.html, html/convert.html, html/customize.html, html/feedback.html, html/login.html, html/recipe_hub.html, html/scale.html, html/signup.html, index.html
changed the folder name from views to html and fixed the index file accordingly.
issue id #323 
tested locally, working properly.
no errors encountered in test run of pages!
=> the server is taking html folder by default!

index.html, public/css/auth.css, public/css/index.css
Updated the CSS for the Home page to improve overall UI/UX.
If this PR is merged, then I will continue making further CSS improvements for other pages too.
=> Update Home page CSS

html/about.html, html/convert.html, html/customize.html, html/feedback.html, html/recipe_hub.html, html/scale.html, index.html, public/css/about.css, public/css/convert.css, public/css/customize.css, public/css/feedback.css, public/css/index.css, public/css/recipe_hub.css, public/css/scale.css
this PR addresses issue #336 
- This PR introduces a visually appealing “Scroll to Top” button across the site.
- Smoothly scrolls to the top regardless of current scroll position.
- Includes hover effects and a rainbow gradient animation to match the bakery theme.
- Fully responsive and works consistently on all pages.
- removes old redundant codes in all files for scroll button
=> Add scroll to top button on all pages

README.md, index.html
This PR improves the **README.md** file for **BakeGenuis AI** by fixing grammar mistakes, clarifying instructions, and updating HTML name references for consistency. The changes make the contribution process easier to follow for new contributors and improve the professional tone of the documentation.
**Related issue:** Minor grammar mistakes and unclear wording in the README file that could confuse new contributors.
* Reviewed all README sections for grammar and clarity.
* Verified all links (setup instructions, live preview, issues) are correct and functional.
* Checked that HTML name references match the app UI branding (`BakeGenuis`).
---
=> Improve README clarity and update HTML name references

about.html, assets/css/about.css, assets/js/about.js
Description:
This PR moves the page-specific styles and scripts of about.html into their own dedicated files for better structure and maintainability.
Changes Made:
•	Created assets/css/about.css and moved about.html styles from the global CSS.
•	Created assets/js/about.js and moved about.html JavaScript code from inline/global scripts.
•	Updated about.html to link both new files correctly.
•	Verified that UI and functionality remain unchanged.
Benefits:
•	Cleaner separation of concerns (HTML, CSS, JS)
•	Improved maintainability and scalability
Issue Reference:
Fixes #386
Checklist:
=> Refactor: Separate CSS and JS for about.html into dedicated files

convert.html, customize.html, index.html, scale.html
=> Update color theme

index.html
📝 Description
This PR improves the footer UI by replacing the plain layout with a more engaging and functional design.
Key changes:
📨 Added a newsletter subscription section to encourage user engagement
🔗 Included important navigation links for quick access
📂 Divided the footer into clear sections for better readability
🎨 Applied modern styling to make the footer visually appealing and consistent with the website’s theme
These enhancements make the footer more interactive, user-friendly, and professional-looking.
Reference:
Before:
After:
fixes issue #357
=> Redesigned Footer with Newsletter, Navigation Links & Structured Layout

about.html, assets/css/about.css, assets/js/about.js, convert.html, customize.html, index.html, scale.html
This pull request resolves the issue of inconsistent navigation bar alignment across different pages of the application. Previously, elements within the navbar (like the logo, navigation links, and action buttons) were aligned differently depending on the page, which created a disjointed user experience.
These changes unify the styling to ensure the navbar looks and feels the same everywhere, providing a more professional and predictable UI. The alignment now matches the design of the mentioned in issue #390 .
- **Refactored CSS:** Centralized the primary navbar styling to a common stylesheet to remove page-specific overrides.
- **Standardized Layout:** Used Flexbox/Grid properties to ensure all navbar items are consistently aligned.
- **Applied Consistency:** Updated all relevant page …
=> fix: Standardize navbar alignment across all pages

convert.html, customize.html, index.html, scale.html
issue solved #401 
Implemented a simple login state management system using **localStorage**.  
- Added a login state to track if the user is logged in.  
- When logged in → the login button is hidden and a logout button is shown.  
- Applied this change across all HTML files.  
- Login state is persisted across page refreshes and across different pages using localStorage.  
- Users can log out from any page, which resets the state globally.  
This enhancement does not require a backend authentication server — it only manages the UI state locally.  
- [x ] Bug fix  
- Logged in on multiple pages and confirmed that the **login button disappears** and **logout button appears**.  
- Refreshed the page to confirm that login state is persisted via localStorage.  
- Navigated across different …
=> Implemented Login State Management with localStorage  

about.html, assets/css/about.css, assets/js/about.js
This PR updates the About Us page by:
- Adjusting CSS for improved styling and layout
- Adding a new Contributors section to highlight project collaborators
1.   <img width="1920" height="900" alt="Screenshot (27)" src="https://github.com/user-attachments/assets/55252863-ddaa-46eb-b6ec-3ce9f714d301" />
2.   <img width="1914" height="903" alt="Screenshot (28)" src="https://github.com/user-attachments/assets/ecdd12fd-0a5e-48ee-b0a0-e1414dcb7201" />
3.   <img width="1920" height="913" alt="Screenshot (29)" src="https://github.com/user-attachments/assets/4edadc57-2f55-4245-a03d-9d41e210f27e" />
=> Update About Us page with new styles and contributors section.

about.html, assets/css/about.css, convert.html, index.html, scale.html
This pull request updates the website footer to ensure it is consistent across all pages. The footer now maintains a uniform layout, styling, and content throughout the site, improving overall brand cohesion and user experience.
Additionally, the footer has been enhanced to fully support both dark and light modes, adapting seamlessly to the selected theme for better accessibility and visual harmony.
**Key Changes:**
* Implemented a single, standardized footer component across all pages
* Unified styling (fonts, spacing, colors, and layout)
* Enabled footer compatibility with dark and light modes
**Expected Behavior:**
* The footer looks identical on all pages
* The footer automatically switches styling when the user toggles between dark and light modes
**Reference** …
=> Standardize Footer Across All Pages with Dark/Light Mode Support

convert.html
This update enhances the overall user interface by improving text readability and adding smooth animations to create a more engaging and accessible experience.
**Changes Introduced**
**Theme & Text Visibility**
- Adjusted the color scheme to provide stronger contrast between text and background.
- Fixed readability issues where text blended into similar background colors.
**Animations**
- Added entrance animation to the main heading “Recipe Converter.”
- Introduced floating animations for a smoother and more dynamic UI.
**Impact**
- These improvements make the interface:
- Easier to read and navigate.
- Visually appealing with subtle motion effects.
- More inclusive and accessible for all users.
**Reference**
Before:
After:
Fixes #355 issue.
=> Recipe.convertor

about.html, assets/css/about.css, assets/js/about.js, convert.html, customize.html, scale.html
✅ PR Description
I have implemented dual scroll buttons (⬆ Back to Top & ⬇ Scroll to Bottom) across all pages of the project, ensuring that:
The button styling, gradient, and hover effects are consistent with the Home page design.
Smooth scrolling behavior is applied for both directions.
Code updates were made cleanly in the respective CSS and JS files to maintain modularity.
This enhancement improves site-wide navigation and provides a uniform, user-friendly experience across the entire project.
Please assign Level 3, as this feature was implemented on all pages and I ensured the CSS matches the Home page for consistency
https://github.com/user-attachments/assets/38a4f00e-cabb-4acb-82dd-4f772e2a0342
=> feat: added dual scroll buttons (top & bottom) across all pages

scale.html
This PR focuses on enhancing the **Scale Recipes section** by addressing issues with the previous color scheme, which felt unbalanced and made the section harder to read. The updates introduce a more cohesive and accessible palette that improves contrast, readability, and aesthetics. The goal is to create a more visually appealing section that aligns with the overall design and improves user experience.
* Replaced the old color scheme with a new consistent and accessible palette.
* Improved text-to-background contrast for better readability.
* Adjusted accent colors to ensure they complement the primary design theme.
###Reference
Before:
After:
Fixes #428 issue.
=> Improve UI in Scale Recipes Section

contact.html, index.html
Implemented a fully responsive Contact Us page for BakeGenius.ai.
Added a contact form with name, email, subject, and message fields.
Includes success message feedback on form submission.
Integrated a modern footer with social links (LinkedIn, GitHub, Email), quick links, features, and support sections.
Consistent styling with the main site (navbar, buttons, fonts, and gradients).
Hover effects and gradient buttons for a polished UI.
contact.html: Added new contact page structure.
style.css (inline in page): Added styles for contact form, social links, dark mode, and responsive layout.
script.js (inline in page): Dark mode toggle, mobile menu, and contact form feedback logic.
=> Added Contact Us Page

feedback.html
This PR implements the complete feedback feature , with custom rating type of feedback and a validation form for better functionality
The test has been checked out locally  on live server
=> Added the complete feednack feature

about.html, assets/css/about.css
Please include a summary of the changes and the related issue.  
=> Resolved issue no #436

index.html
Fixed this issue https://github.com/supriya46788/BakeGenuis-AI/issues/477 
=> Typo bug fixed for home page navbar and title

convert.html
I have changed the text color for the subtitle and the recipe placeholder content.  
Issue Number: #478 
=> The color for subtitles are fixed

convert.html, index.html
This PR updates the dark mode for convert recipe page which aligns with the current dark theme. 
Fixes #506 
##Screenshots
=> Updated CSS and Color Layout in dark mode for Convert recipe page

faq.html, index.html
closes: #465 
This PR introduces a new FAQ (Frequently Asked Questions) page to improve user onboarding and provide quick answers to common queries.
**Changes Made:**
Added a new file faq.html with:
Accordion-style FAQ layout for better readability.
Responsive and mobile-friendly design.
Consistent theme with the BakeGenius-AI site.
Updated navbar in index.html to include a FAQ link.
Implemented JavaScript toggle for expanding/collapsing FAQ answers.
**Why This Change?**
Helps new users understand how to use BakeGenius-AI effectively.
Reduces confusion around generating recipes, inputting ingredients, and troubleshooting.
Enhances the overall user experience.
=> Added FAQ section

about.html, assets/css/about.css, assets/js/about.js, convert.html, customize.html, index.html, scale.html
This PR fixes two theme-related UI issues:
- In **light mode**, the Login button now has a dark brown background for better visibility and brand consistency.
- In **dark mode**, the About section now loads with a proper dark background to maintain theme consistency.
Fixes #505
- Switched between **light mode** and **dark mode**.
- Verified that the Login button in light mode has a dark brown background.
- Verified that clicking "About" in dark mode correctly loads with a dark background.
=> fix(#505): correct login button color in light mode and About section theme in dark mode

customize.html, faq.html, scale.html
This PR updates the Scale Recipes Page with the new color palette and improved CSS styling. The goal is to provide a more consistent, accessible, and visually appealing user experience that aligns with the latest design standards.
Fixes #533
##Screenshots
=> Improve CSS and styling in dark mode for FAQ page

about.html, assets/css/about.css, convert.html, customize.html, faq.html, feedback.html, index.html, scale.html
=> Updated navbar

assets/css/about.css, assets/js/about.js
Implemented dark mode support for the about.html page.
Added JavaScript code in about.js to handle dark mode toggle button logic.
Applied a dark-mode class in body tag on toggle.
Extended CSS for hero section, section cards, scroll buttons, contributors, and footer to ensure proper dark theme styling.
Preserved user theme preference using localStorage.
Closes #519
Manually tested by clicking the dark mode toggle button on about.html.
Verified that the dark-mode class is applied/removed correctly.
Confirmed styles update without layout or readability issues.
Reloaded the page to ensure the saved theme preference from localStorage persists.
=> Implemented dark/light mode toggle on About Us page

index.html
- ✨ Unified input field styling (username, password, etc.)
- 🎨 Added icons with focus-based color highlights
- 🪶 Refined placeholder text for better readability
- 🧩 Removed default form borders, replaced with subtle shadows and soft background
- 📱 Improved spacing and alignment for better responsiveness
#508 
- ✅ Manually tested the Login and Signup forms in the browser
- ✅ Verified focus states on input fields and icons
- ✅ Checked responsiveness across desktop, tablet, and mobile views
- ✅ Ensured that all inputs and buttons remain functional after UI changes
=> style(auth): improve login and signup form UI

assets/css/about.css
This PR enhances the About page styling to align with the overall design of the application. The CSS has been refined to match the look and feel of other pages, ensuring a consistent user experience across the site.
Fixes Issue #430 
BEFORE:
AFTER:
=> Improve About Page CSS for Consistency Across Application

index.html
This PR improves the styling of the hamburger menu on the Home page so it aligns with the CSS used on the homepage. The goal is to maintain a consistent user interface and design system across the application.
Fixes Issue #539 
- Updated hamburger menu CSS to match homepage styles
- Adjusted spacing, colors, and hover states for consistency
- Verified responsiveness across devices
- Ensured dark/light theme compatibility
BEFORE:
AFTER:
=> Refine Hamburger Menu CSS for Consistency with Homepage

contact.html
This PR updates the Contact us Page with the new color palette and improved CSS styling. The goal is to provide a more consistent, accessible, and visually appealing user experience that aligns with the latest design standards.
Fixes #547
##Screenshots
=> Improve dark mode css in Contact us page

.vscode/settings.json, scale.html
Reverts supriya46788/BakeGenuis-AI#524
=> Revert "Issue #493 fixed (Added dynamic recipe scaling features)"

assets/css/about.css
Updated the dark mode in About page
=> Fix: Updated dark mode in about page

feedback.html
This PR updates the Feedback Page with the new color palette and improved CSS styling in dark mode. The goal is to provide a more consistent, accessible, and visually appealing user experience that aligns with the latest design standards.
Fix #583
##Screenshots
=> Improve Dark theme CSS and layout of feedback section

reportissue.html
I added the report issue page which matches the theme of the website.
- [ yes] New feature
I ran it locally and found no bugs.
- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my code
- [yes ] I have commented my code where necessary
- [yes ] I have added tests that prove my fix is effective or that my feature works
- [ yes] I have made corresponding changes to the documentation
=> issue #456 Update reportissue.html

scale.html
This PR improves the dark mode experience on the Scale Your Recipes page.
- Enhanced contrast for input fields, text, and buttons.
- Improved visual hierarchy to make the form easier to navigate and interact with.
Closes  #563
- Verified changes in local development environment with dark mode enabled.
- Checked input fields, buttons, and text for proper visibility and contrast.
- Ensured that the changes do not affect light mode styling.
=> fix(ui): improve dark mode UX on Scale Your Recipes page (#563)

helpcenter.html
=> fix: Create and style Help Center page

contact.html
This PR improves the Contact Us page by adding missing details and enhancing the overall UI/UX. The page now provides better usability, modern visuals, and improved accessibility for users.
- Added social media links and essential contact details (email, phone, website)
- Improved form layout with proper labels and input styling
- Updated color gradients and button design for a modern look
- Refined box shadows for softer, premium elevation
- Enhanced readability and accessibility across devices
#608 Issue No
@supriya46788  PLEASE CHECK
=> Enhancement/contact us UI ux 608

index.html
Description:
Fixed the issue where the login page was not opening and added dark mode support for the login and signup pages.  
Closes #561
Type of change:
How Has This Been Tested?
- Verified that the login modal now opens correctly when the login button is clicked.
- Tested the toggle between login and signup forms.
- Checked dark mode toggle to ensure proper styling is applied for both login and signup pages.
- Tested on multiple browsers to confirm functionality.
https://github.com/user-attachments/assets/5b3f4c3f-de72-4e5b-9ed3-3b13116a8b3d
Checklist:
- [x ] I have made corresponding changes to the documentation
=> 🐛 [Fix] Resolve login page issue and add dark mode support

faq.html
This PR fixes the inconsistent CSS styling of the *login button* in light mode on the FAQs page.
Previously, the button looked different compared to other pages, breaking the UI consistency.
Now, the login button on the FAQs page matches the global style used across the project.
fixes Issue #634 
Updated login button CSS on FAQs page to align with other pages in light mode.
Ensured consistency in color, padding, and hover state.
=> fix: unify login button CSS in light mode on FAQs page

scale.html
**Summary**
This PR addresses design and readability issues in the "Scale Recipe" section. The heading, text, and icon have been updated to improve visual appeal and consistency across light and dark modes.
**Changes Made**
1. Updated the heading styles to ensure good contrast and readability in both light and dark modes.
2. Adjusted the text color for better visibility in light mode.
3. Replaced the beam balance icon with a brown version (or emoji) that complements the site’s overall color palette.
**Reference**
Fixes #611 issue.
=> Improve "Scale Recipe" Section Styling

helpcenter.html
This PR resolves the layout and styling issues on the Help Center page. The page was previously missing proper CSS styling, causing misalignment, inconsistent spacing, and readability issues. The changes include:
- Added container styling for proper alignment and max-width.
- Improved spacing and padding for headings, descriptions, and sections.
- Applied consistent font styles and sizes.
- Fixed responsive behavior for different screen sizes.
#623 Issue No
=> fix: add missing CSS styling to Help Center page layout (#623)

about.html, assets/css/about.css
This PR fixes issue #710 by correcting the footer layout and alignment on the About Us page.
Adjusted CSS in about.css to ensure proper spacing and alignment
Made footer responsive and consistent with other pages
Verified layout across different screen sizes
Opened the About Us page in browser
Checked footer alignment and layout visually
**Before 
**After
=> Fixes #710: Corrected footer layout and alignment in About Us page

assets/css/chatbot.css, assets/js/chatbot.js, index.html
Added a chatbot  where a person can interact and can understand about website more easily.Added it in the navbar section so it can be easily visible.
=> Added Chatbot 

index.html
Improved the homepage, **added stats , How It Works, why to choose section in the homepage**.Revamped overall homepage styling with improved spacing, hover effects, and typography.
- Added How It Works section to guide users through the recipe conversion process.
- Added Stats section highlighting recipe conversions, accuracy rate, happy bakers, and AI availability.
- Added Why Professional Bakers Use Grams section to explain the benefits of precision in baking.
- Enhanced dark mode support with better contrast and gradient adjustments.
- Improved feature cards design (hover animations, consistent icons, glassmorphism style).
#664 Issue No
=> Revamp homepage styling and add essential sections #664

assets/css/about.css
The PR is about the changes made for Scroll bar UI  and made it consistent by removing the unwanted
BEFORE:
**AFTER:**
=> Changed the Scrollbar to the normal one for  better UI

about.html, convert.html, customize.html, scale.html
=> Removed floating elements

assets/css/about.css, assets/css/contact.css, assets/css/convert.css, assets/css/customize.css, assets/css/faq.css, assets/css/feedback.css, assets/css/helpcenter.css, assets/css/index.css, assets/css/privacypolicy.css, assets/css/reportissue.css, assets/css/scale.css, assets/css/toc.css, scale.html
This PR fixes an issue where the navbar links would overlap at specific viewport dimensions across multiple pages. 
Fix #779
##Screenshots
=> Fix: Navbar links layout breaking at certain viewport sizes.

assets/css/about.css, assets/css/faq.css
Description:
This PR updates the heading animations in the About and FAQs sections to match the style used across other pages.
- Ensures consistent animation behavior site-wide.
- Improves overall UI/UX cohesion.
Fixes #785 issue .
=> Fix inconsistent heading animations in About and FAQs sections

assets/css/contact.css, contact.html
This PR makes UI improvements to the Contact Us section for better consistency and alignment with the site’s overall design.
- Standardized heading sizes for a uniform look.
- Updated the color of “Let’s Get in Touch” to match the site’s theme and vibe.
These changes enhance readability and ensure the section feels cohesive with the rest of the site.
**Reference:**
Ater:
Fixes #801 issue.
=>  Improve UI consistency in Contact Us section

assets/css/helpcenter.css
Please include a summary of the changes and the related issue.  
=> Update helpcenter.css Issue no 794

about.html, assets/css/about.css, assets/css/customize.css, assets/css/faq.css, assets/css/scale.css, faq.html
This PR fixes inconsistencies in page title styling across the site.
- Unified spacing (margins and padding).
- Standardized font sizes for titles to maintain hierarchy.
- Applied a consistent text color that matches the design system.
These updates ensure page titles now look consistent, improving overall readability and visual cohesion across sections.
**Reference:**
Fixes #800 issue.
=>  Standardize page title styling across all sections

assets/css/convert.css
This PR closes #804 
In this PR I changed the placeholder text's color and I also changed the color of the main card in the convert page. This changes will be visible in the dark mode.
=> Did some changed in the dark mode of convert.css

about.html, contact.html, convert.html, customize.html, faq.html, feedback.html, helpcenter.html, index.html, privacypolicy.html, reportissue.html, scale.html, toc.html
Updated the footer structure to ensure consistent navigation across all pages.  
Previously, the "Support" section contained more links than the others, creating imbalance.  
Now, the footer has three clearly defined sections: **Quick Links, Features, and Support**.
- Added **Quick Links**: Home, Convert Recipe, Customize, Scale Recipe, About Us, FAQ
- Added **Features**: Unit Conversion, Nutritional Analysis, Recipe Scaling, AI Optimization, Mobile Friendly, Blog
- Updated **Support**: Contact Us, Help Center, Feedback, Report Issue, Privacy Policy, Terms of Services
- Ensured uniform alignment, styling, and structure across all pages
@supriya46788 If it fits, could you please assign label for this PR
=> Reorganized footer with consistent Quick Links, Features, and Support sections

assets/css/index.css, index.html
This PR closes #843 
I made some changes in the index.html and index.css to make to remove the hand cursor for the non clickable links
Please check it out.
=> Removed hand cursor for non clickable cards in the footer

reportissue.html
Description
This PR adds a scroll button on the reportissue.html page, allowing users to quickly navigate to the top or bottom of the page. It improves user experience and accessibility for longer forms or content.
Type of change
•	New feature
How Has This Been Tested?
•	Verified the scroll button appears correctly on different screen sizes.
•	Tested smooth scrolling to both top and bottom of the page.
•	Ensured existing page functionality remains unaffected.
Checklist:
•	My code follows the style guidelines of this project
•	I have performed a self-review of my code
•	I have commented my code where necessary
•	I have added tests that prove my fix is effective or that my feature works
•	I have made corresponding changes to the documentation
Screenshots:
Fixes ISSUE NO. #826
=> Add Scroll Button for Report Issue Page

blog.html
Description:
This PR enhances the blog.html page to fully match the website’s UI, supporting both dark and light modes while maintaining a responsive layout. The update ensures a consistent and modern look across devices and themes.
Changes Made:
•	Updated colors, fonts, buttons, and layout to match the main website theme.
•	Implemented dark mode and light mode support for seamless theme switching.
•	Ensured responsive design for desktop, tablet, and mobile screens.
•	Maintained all existing blog functionality.
Testing Done:
•	Verified UI consistency with the rest of the website in both light and dark modes.
•	Checked readability, button/link visibility, and hover effects for all modes.
•	Tested page responsiveness on multiple screen sizes and devices.
Notes:
•	No breaking changes …
=> Update Blog Page UI with Dark & Light Mode and Responsive Design
